services:
  seq:
    image: gcp-emulators/seq:2024.1
    build:
      context: ./src/infra/seq/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
    networks:
      - default
    expose:
      - 80
      - 5341
    ports:
      - ${SEQ_UI_PORT}:80
      - ${SEQ_INGESTION_PORT}:5341

  gcp-emulators:
    image: gcp-emulators:535.0.0-emulators
    build:
      context: ./src
      dockerfile: infra/gcp-emulators/Dockerfile
    restart: always
    command: >
      bash -c "gcloud beta emulators pubsub start --project=${PROJECT_ID} --host-port='0.0.0.0:${GCP_EMULATORS_PORT}'"
    volumes:
      - gcp-emulators-config:/config
      - gcp-emulators-certs:/certs
    networks:
      default:
    expose:
      - ${GCP_EMULATORS_PORT}
    ports:
      - ${GCP_EMULATORS_PORT}:${GCP_EMULATORS_PORT}

volumes:
  seq-data:
  gcp-emulators-config:
  gcp-emulators-certs:

networks:
  default:
    name: gcp-emulators-poc_default
